name: "Deployment via Ansible"
on:
  workflow_call:
    inputs:
      aws_region:
        required: false
        type: string
        default: "eu-west-1"
      ansible_playbook:
        required: false
        type: string
        default: "apps.yml"
      ansible_repo:
        required: true
        type: string
      ansible_repo_ref:
        required: false
        type: string
        default: "main"
      deploy: # Output from build stage
        required: true
        type: string
      host_prefix: # used by ssh config
        required: true
        type: string
      key: # Output from build stage
        required: true
        type: string
      tag: # Output from build stage
        required: true
        type: string
    secrets:
      ansible_vault_password:
        required: true
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      github_pat:
        required: true
      ssh_key:
        required: true

jobs:
  deploy:
    name: "Deploy via Ansible"
    runs-on: ubuntu-20.04
    if: inputs.deploy != ''
    steps:
    - name: "SSH Setup: github -> aws"
      uses: shimataro/ssh-key-action@v2
      with:
        key: "${{ secrets.ssh_key }}"
        known_hosts: unnesessary

    - name: "Install Ansible"
      uses: epimorphics/github-actions/ansible@v9
      with:
        aws-access-key-id: "${{ secrets.aws_access_key_id }}"
        aws-secret-access-key: "${{ secrets.aws_secret_access_key }}"
        aws-region: "${{ inputs.aws_region }}"
        host-prefix: "${{ inputs.host_prefix }}"

    - name: "Ansible Deployment Repository Checkout"
      id: deploy
      uses: actions/checkout@v2
      with:
        repository: "${{ inputs.ansible_repo }}"
        ref: "${{ inputs.ansible_repo_ref }}"
        token: "${{ secrets.github_pat }}"

    - name: "Ansible Deploy"
      if: ( inputs.tag != '' && inputs.deploy != '' )
      uses: epimorphics/github-actions/ansible-deploy-image@v9
      with:
        secret: "${{ secrets.ansible_vault_password }}"
        stage: "${{ inputs.deploy }}"
        name: "${{ inputs.key }}"
        version: "${{ inputs.tag }}"
        playbook: "${{ inputs.ansible_playbook }}"

    - name: "Git Commit"
      if: inputs.tag != ''
      shell: bash
      run: |
        if ! git diff --quiet
        then
          git config --global user.name "Github CICD"
          git config --global user.email "noreply@epimorphics.com"
          git commit -am "Github/CICD: ${{ inputs.deploy }}/${{ inputs.key }}:${{ inputs.tag }}"
          git push
        else
          echo "No changes to commit"
          echo "tag: ${{ inputs.tag }}"
        fi
