name: "Publish Docker Image"
on:
  workflow_call:
    inputs:
      aws_region:
        description: "AWS region of ECR"
        required: false
        default: "eu-west-1"
      image:   # Output from build stage
        description: "Docker Image Name"
        required: true
      publish: # Output from build stage
        description: "ECR Subdirectory"
        required: true
      tag:     # Output from build stage
        description: "Docker image Tag"
        required: true
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      epi_gpr_access_token:
        required: true

jobs:
  publish:
    name: "Upload Docker Image to ECR"
    runs-on: ubuntu-20.04
    if: ( inputs.image != '' && inputs.publish != '' && inputs.tag != '' )
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws_access_key_id: "${{ secret.aws_access_key_id }}"
        aws_secret_access_key: "${{ secret.aws_secret_access_key }}"
        aws_region: "${{ inputs.aws_region }}"

    - name: "Login to Amazon ECR"
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: "Create ECR area"
      uses: epimorphics/github-actions/create-ecr-action@v6
      with:
        image: ${{ inputs.image }}/${{ inputs.publish }}

    - name: "Publish image"
      env:
        IMAGE: ${{ inputs.image }}/${{ inputs.publish }}
        TAG: ${{ inputs.tag }}
      shell: bash
      run: |
        PAT=${{ secrets.epi_gpr_access_token }} make publish
