name: "Bulid & Publish Docker Image"
on:
  workflow_call:
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      epi_gpr_access_token:
        required: true
    outputs:
      deploy:
        description: "The deployment environment"
        value: ${{ jobs.build.outputs.deploy }}
      key:
        description: "The Ansible to use in deployment"
        value: ${{ jobs.build.outputs.key }}
      tag:
        description: "The tag of the built docker image"
        value: ${{ jobs.build.outputs.tag }}

jobs:
  publish:
    name: "Build & Upload Docker Image to ECR"
    runs-on: ubuntu-20.04
    outputs:
      deploy: ${{ steps.mapper.outputs.deploy }}
      key: ${{ steps.mapper.outputs.key }}
      publish: ${{ steps.mapper.outputs.publish }}
      tag: ${{ steps.gittag.outputs.tag }}

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Mapped deployment"
      id: mapper
      uses: epimorphics/github-actions/mapper@v6
      with:
        ref: "${{github.ref}}"

    - name: "Get image tag"
      id: gittag
      uses: epimorphics/github-actions/generate-tag@v6

    - name: "Debug"
      shell: bash
      run: |
        echo IMAGE: "${{ steps.mapper.outputs.image }}/${{ steps.mapper.outputs.publish }}"
        echo TAG: "${{ steps.mapper.gittag.tag }}"

    - name: "Create image"
      if: steps.mapper.outputs.image != ''
      env:
        REPO: ${{ steps.mapper.outputs.image }}
      shell: bash
      run: |
        PAT=${{ secrets.epi_gpr_access_token }} make image

    - name: "Configure AWS Credentials"
      if: ( steps.mapper.outputs.image != '' && steps.mapper.outputs.publish != '' && steps.mapper.gittag.tag != '' )
      uses: "aws-actions/configure-aws-credentials@v1"
      with:
        aws-access-key-id: "${{ secrets.aws_access_key_id }}"
        aws-secret-access-key: "${{ secrets.aws_secret_access_key }}"
        aws-region: "${{ inputs.aws_region }}"

    - name: "Login to Amazon ECR"
      if: ( steps.mapper.outputs.image != '' && steps.mapper.outputs.publish != '' && steps.mapper.gittag.tag != '' )
      id: "login-ecr"
      uses: "aws-actions/amazon-ecr-login@v1"

    - name: "Create ECR area"
      if: ( steps.mapper.outputs.image != '' && steps.mapper.outputs.publish != '' && steps.mapper.gittag.tag != '' )
      uses: "epimorphics/github-actions/create-ecr-action@v6"
      with:
        image: "${{ steps.mapper.outputs.image }}/${{ steps.mapper.outputs.publish }}"

    - name: "Publish image"
      if: ( steps.mapper.outputs.image != '' && steps.mapper.outputs.publish != '' && steps.mapper.gittag.tag != '' )
      env:
        IMAGE: "${{ steps.mapper.outputs.image }}/${{ steps.mapper.outputs.publish }}"
        TAG: "${{ steps.mapper.gittag.tag }}"
      shell: bash
      run: |
        PAT=${{ secrets.epi_gpr_access_token }} make publish
